<html>
<head>
<script type='text/javascript' src='http://localhost:8888/wordpress/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>
	<script type='text/javascript' src='electives.js'></script>
	<style type="text/css">
		#input {
			display: none;
		}
		td > ul {
			list-style-type: none;
			margin: 0px;
		}
	</style>
</head>
<body>
<button type="button" onclick="upload()">Upload</button>
<table id="output" border="1">
	<thead><tr><td>Student</td><td>Keywords</td><td>Poster</td><td>Summary</td></tr></thead>
</table>
<ul id="input">
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Craig-Wylie_29_assignsubmission_file_3-Australia-EM-eposter.pdf">Australia &#8211; Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Craig-Wylie_29_assignsubmission_file_2-Australia-EM-elective-summary.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kar-Jun-Yip_38_assignsubmission_file_2-poster.YipKar-Jun-Australia-Gastroenterology-Eposter.pdf">Australia &#8211; Gastroenterology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kar-Jun-Yip_38_assignsubmission_file_2-Summary-of-elective-in-Australia-Gastroenterology.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amy-Johnstone_346_assignsubmission_file_3-poster-Australia-emergency-medicine.pdf">Australia &#8211; Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amy-Johnstone_346_assignsubmission_file_2-elective-summary-Australia-Emergency-medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rebecca-Matchett_329_assignsubmission_file_3-poster-australia-anaesthetics.pdf">Australia &#8211; Anaesthetics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rebecca-Matchett_329_assignsubmission_file_2-elective-summary-australia-anaesthetics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rosie-Wilson_340_assignsubmission_file_Poster_Australia_Paediatrics.pdf">Australia &#8211; Paediatrics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rosie-Wilson_340_assignsubmission_file_Summary_Australia_Paediatrics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Shona-Mcdonald_333_assignsubmission_file_3-poster-Australia-paediatrics.pdf">Australia &#8211; Paediatrics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Shona-Mcdonald_333_assignsubmission_file_2-summary-Australia-paediatrics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ailsa-Gellan_1093_assignsubmission_file_3-Poster-Australia-Indigenous-Health.pdf">Australia &#8211; Indigenous Health ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ailsa-Gellan_1093_assignsubmission_file_2-Summary-Australia-Indigenous-Health.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Hannah-Cuthbertson_547_assignsubmission_file_Poster-Australia-Anaesthetics.pdf">Australia &#8211; Anaesthetics ePoster</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Lauren-Copeland_540_assignsubmission_file_3-poster-Australia-Primary-Health-Care.pdf">Australia &#8211; Primary Health Care ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Lauren-Copeland_540_assignsubmission_file_2-Summary-Australia-Primary-Health-Care.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Matthew-Balfour_574_assignsubmission_file_Poster-Australia-Paediatrics-and-ICU.pdf">Australia &#8211; ICU and Paediatrics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Matthew-Balfour_574_assignsubmission_file_1-Elective-report-Australia-ICU-Paeds.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Olivia-Curran_572_assignsubmission_file_3-Poster-Australia-Indigenous-Healthcare.pdf">Australia &#8211; Indigenous Healthcare ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Olivia-Curran_572_assignsubmission_file_2-Elective-Summary-Australia-Indigenous-Healthcare.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sarah-Blue_567_assignsubmission_file_3-poster-Australia-indigineous-community-medicine.pdf">Australia &#8211; Indigenous Community Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sarah-Blue_567_assignsubmission_file_2-Summary-Australia-Indigenous-Community-Medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Thomas-Leung_565_assignsubmission_file_Poster-Australia-Intensive-care-and-Endocrine.pdf">Australia &#8211; Intensive Care &amp; Endocrine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Thomas-Leung_565_assignsubmission_file_Summary-Australia-Intensiver-Care-and-Endocrine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ujani-Basu_555_assignsubmission_file_3-poster-Australia-OG.pdf">Australia &#8211; Obs &amp; Gynae ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ujani-Basu_555_assignsubmission_file_2-elective-summary-Australia-OG.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Adam-Harrigan_1127_assignsubmission_file_3-poster-Australia-Emergency-Medicine.pdf">Australia &#8211; Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Adam-Harrigan_1127_assignsubmission_file_2-summary-Australia-Emergency-Medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ai-Hew_1129_assignsubmission_file_3-poster-Australia-Accident-and-Emergency.pdf">Australia &#8211; A &amp; E ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ai-Hew_1129_assignsubmission_file_2-summary-Australia-Accident-and-Emergency.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Francesca-Mastaglio_1111_assignsubmission_file_Poster-Australia-Respiratory-medicine.pdf">Australia &#8211; Respiratory Medicine ePoster</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jessica-Seymour_1130_assignsubmission_file_3-poster-Germany-and-Austria-Anaesthetics-and-Intensive-Care.pdf">Austria / Germany &#8211; Anaesthetics and Intensive Care ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jessica-Seymour_1130_assignsubmission_file_2-elective-summary-Germany-and-Austria-Anaesthetics-and-Intensive-Care.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amy-Stewart_311_assignsubmission_file_Poster-Belize-General-Medicine.pdf">Belize &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amy-Stewart_311_assignsubmission_file_Elective-summary-belize-general-medicine-.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Frances-Butterworth_312_assignsubmission_file_3-poster-Belize.pdf">Belize ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Frances-Butterworth_312_assignsubmission_file_2-elective-summary-Belize.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Lisa-Moore_321_assignsubmission_file_poster-belize-GPGeneral-Medicine.pdf">Belize &#8211; General Practice &amp; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Lisa-Moore_321_assignsubmission_file_elective-summary-Belize-GPGeneral-Medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Alice-Lindgren_543_assignsubmission_file_PosterUSAandBelizeAcuteCareGeneralMedicine.pdf">Belize &#8211; Acute &amp; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Alice-Lindgren_543_assignsubmission_file_Elective-summary-USA-Belize-Acute-Med-Gen-Med.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Yee-Wong_549_assignsubmission_file_poster-country-specialty.pdf">Borneo &#8211; Obs &amp; Gynae and Ophthalmology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Yee-Wong_549_assignsubmission_file_elective-summary-country-specialty-.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Alix-Morieux_1123_assignsubmission_file_3-poster-Barbados-Psychiatry.pdf">Barbados &#8211; Psychiatry ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Alix-Morieux_1123_assignsubmission_file_2-elective-summary-Barbados-psychiatry.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Caitlin-Whittaker_1101_assignsubmission_file_3-poster-belize-general-medicine.pdf">Belize &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Caitlin-Whittaker_1101_assignsubmission_file_2-elective-summary-belize-general-medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Calum-Kerr_1106_assignsubmission_file_3-Poster-Belize-Emergency.pdf">Belize &#8211; Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Calum-Kerr_1106_assignsubmission_file_2-Summary-Belize-Emergency.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Chloe-Donaldson_1099_assignsubmission_file_3-Poster-General-Belize.pdf">Belize &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Chloe-Donaldson_1099_assignsubmission_file_2-Elective-Summary-Belize-General.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/George-Hawche_1112_assignsubmission_file_3.-Poster-Barbados-General-Medicine.pdf">Barbados &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/George-Hawche_1112_assignsubmission_file_2.-Summary-Barbados-General-Medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Hannah-Mccauley_1103_assignsubmission_file_poster-Barbados-Anaesthetics.pdf">Barbados &#8211; Anaesthetics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Hannah-Mccauley_1103_assignsubmission_file_summary-Barbados-Anaesthetics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jen-Corner_1136_assignsubmission_file_3-poster-Barbados-Ortho.pdf">Barbados &#8211; Orthopaedics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jen-Corner_1136_assignsubmission_file_2-Elective-Summary-Barbados-Orthopaedics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Melanie-Foy_1124_assignsubmission_file_Poster-Barbados-ObsGynae.pdf">Barbados &#8211; Obs &amp; Gynae ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Melanie-Foy_1124_assignsubmission_file_elective-summary-barbados-ObsGynae.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sylvia-Okwemba_1102_assignsubmission_file_Poster-Barbados-Infectious-Diseases.pdf">Barbados &#8211; Infectious Diseases ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sylvia-Okwemba_1102_assignsubmission_file_Summary-Barbados-Infectious-Diseases.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/David-Mackinlay_40_assignsubmission_file_3-Canada-EM-eposter.pdf">Canada &#8211; Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/David-Mackinlay_40_assignsubmission_file_2-elective-Canada-EM-summary.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Evan-Marback_36_assignsubmission_file_Canada_Palliative_Care_Oncology_Elective-Poster-A.pdf">Canada &#8211; Palliative Care/Oncology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Evan-Marback_36_assignsubmission_file_Summery-Canada-GpPalliative-care.pdf">Summery sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Hannah-Dally_23_assignsubmission_file_3-Canada-EM-eposter.pdf">Canada &#8211; Rural Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Hannah-Dally_23_assignsubmission_file_2-elective-Canada-REM-summary.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kristy-Armstrong_319_assignsubmission_file_3-poster-Canada-Plastics.pdf">Canada &#8211; Plastic Surgery ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kristy-Armstrong_319_assignsubmission_file_2-elective-summary-Canada-Plastics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Naomi-Foster_544_assignsubmission_file_3-poster-canadauk-orthopaedics.pdf">Canada and UK &#8211; Orthopaedics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Naomi-Foster_544_assignsubmission_file_2-elective-summary-CanadaUK-Orthopaedics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Simon-Clark_541_assignsubmission_file_3-Poster-Canada-Ortho.pdf">Canada &#8211; Orthopaedics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Simon-Clark_541_assignsubmission_file_2-Elective-Summary-Canada-Ortho.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Aislinn-Browne_1131_assignsubmission_file_3-elective-poster-Cayman-Islands-A-E.pdf">Caymen Islands &#8211; A &amp; E ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Aislinn-Browne_1131_assignsubmission_file_2-elective-summary-Cayman-Islands-A-E.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Andrew-Melvin_551_assignsubmission_file_3-poster-South-Africa-Anaesthetics.pdf">Durban (South Africa) &#8211; Anaesthetics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Andrew-Melvin_551_assignsubmission_file_2-elective-summary-ÔÇô-Durban-Anaesthetics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Fraser-Peck_313_assignsubmission_file_3-poster-London-OphthalmologyOrthopaedics.pdf">England, London &#8211; Ophthalmology/Orthopaedics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Fraser-Peck_313_assignsubmission_file_2-elective-summary-London-OphthalmologyOrthopaedics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Mohamed-Elseedawy_402_assignsubmission_file_Poster-ÔÇô-Egypt-Oncology.pdf">Egypt &#8211; Oncology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Mohamed-Elseedawy_402_assignsubmission_file_Summary-Egypt-Oncology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Heather-Lockwood_548_assignsubmission_file_3-poster-UK-forensic-pathology.pdf">England, Leicester &#8211; Forensic Pathology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Heather-Lockwood_548_assignsubmission_file_2-elective-summary-UK-forensic-pathology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Iona-Campbell_1669_assignsubmission_file_Poster-Summary-UK-Elective.pdf">England, Leeds &#8211; Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Iona-Campbell_1669_assignsubmission_file_Poster-Summary-UK-Elective1.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jean-Wiedmann_53_assignsubmission_file_Poster-Fiji-General-Medicine.pptx">Fiji-General Medicine</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jean-Wiedmann_53_assignsubmission_file_Summary-Fiji-General-Medicine.docx">Summary &#8211; Fiji &#8211; General Medicine</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kate-Millar_45_assignsubmission_file_3-poster.pdf">Fiji &#8211; General and Community Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kate-Millar_45_assignsubmission_file_2-Fiji-Gen-and-Comm-Med-elective-summary.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Melissa-Vipond_35_assignsubmission_file_3-poster-Fiji-Gen-Med.pdf">Fiji &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Melissa-Vipond_35_assignsubmission_file_2-elective-summary-Fiji-Gen-Med.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/John-Prentice_32_assignsubmission_file_Poster-Ghana-General-Med.pdf">Ghana-General Med ePoster</a> and  <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/John-Prentice_32_assignsubmission_file_Summary-Ghana-General-Med.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jane-Simpson_570_assignsubmission_file_3.-Poster-Grenada-West-Indies-Gen-Med-Paeds.pdf">Grenada (West Indies) &#8211; General Medicine &amp; Paediatrics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jane-Simpson_570_assignsubmission_file_2.-Elective-Summary-Grenada-Gen-Med-Paeds.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jenni-Pearson_545_assignsubmission_file_Poster-Grenada-West-Indies-Obs-Gynae-General-Medicine.pdf">Grenada (West Indies) &#8211; Obs &amp; Gynae and General Medicine</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jenni-Pearson_545_assignsubmission_file_Summary-Grenada-West-Indies-Obs-and-Gynae-General-Medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jessica-Seymour_1130_assignsubmission_file_3-poster-Germany-and-Austria-Anaesthetics-and-Intensive-Care.pdf">Germany / Austria &#8211; Anaesthetics and Intensive Care ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jessica-Seymour_1130_assignsubmission_file_2-elective-summary-Germany-and-Austria-Anaesthetics-and-Intensive-Care.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nathan-Wilson_56_assignsubmission_file_3-Elective-Poster-Hawaii-USA-NZ-Military-Med.pdf">Hawaii &#8211; USA &#8211; New Zealand &#8211; Military Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nathan-Wilson_56_assignsubmission_file_2-Elective-Summary-Hawaii-USA-NZ-Military-Med.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kerrie-Fitzgerald_46_assignsubmission_file_poster-Ireland-emergency-medicine.pdf">Ireland-Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kerrie-Fitzgerald_46_assignsubmission_file_Summary-Ireland-emergency-department.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amala-Francis_320_assignsubmission_file_poster-india-paeds_community_health_emergency-med.pdf">AIndia &#8211; Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amala-Francis_320_assignsubmission_file_summary-india-paeds_community_health_emergency-med.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nicholas-Woo_330_assignsubmission_file_3-poster-India-multiple.pdf">India &#8211; Multiple diciplines ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nicholas-Woo_330_assignsubmission_file_2-elective-summary-India-multiple.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Robert-Jenkins_348_assignsubmission_file_poster-india-mixed.pdf">India &#8211; Multiple Disciplines ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Robert-Jenkins_348_assignsubmission_file_Summary-India-Mixed.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sarah-Mcluckie_316_assignsubmission_file_3-poster-India-multiple.pdf">India &#8211; Multiple diciplines ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sarah-Mcluckie_316_assignsubmission_file_2-elective-summary-India-multiple.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Scott-Kendall_55_assignsubmission_file_Kendall-Scott-Johannesburg-Trauma.pdf">Johannesburg (South Africa) &#8211; Trauma ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Scott-Kendall_55_assignsubmission_file_Elective-Summary_Johannesburg-Trauma.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Fiona-Robertson_344_assignsubmission_file_Poster-Japan-Anaesthetics.pdf">Japan &#8211; Anaesthetics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Fiona-Robertson_344_assignsubmission_file_Summary-Japan-Anaesthetics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kwun-Chan_1098_assignsubmission_file_3-Poster-Japan-Cardiovascular-Surgery-and-Nephrology-Endocrinology-and-Metabolism.pdf">Japan &#8211; Cardiovascular Surgery / Nephrology / Endocrinology / Metabolism ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kwun-Chan_1098_assignsubmission_file_2-Summary-Japan-Cardiovascular-Surgery-and-Nephrology-Endocrinology-and-Metabolism.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Anna-Wells_58_assignsubmission_file_3-poster-Malta-Wales-Scotland-Acute-and-Emergency.pdf">Malta Wales Scotland &#8211; Acute and Emergency</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Anna-Wells_58_assignsubmission_file_2-summary-Malta-Wales-Scotland-Acute-and-Emergency.pdf">summary &#8211; Malta Wales Scotland &#8211; Acute and Emergency</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Elizabeth-Pang_26_assignsubmission_file_3-poster.pdf">Malaysia &#8211; Gen Med/Ophthalmology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Elizabeth-Pang_26_assignsubmission_file_2-elective-Malaysia-Gen-Med-Ophthalmology-summary.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Megan-Chamberlain_24_assignsubmission_file_2-Poster-Malawi-General-Medicine.pdf">Malawi &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Megan-Chamberlain_24_assignsubmission_file_3-Summary-Malawi-General-Medicine.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sarah-Alfred_80_assignsubmission_file_3-Poster-Malaysia-Gen-Med.pdf">Malaysia &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sarah-Alfred_80_assignsubmission_file_2-Elective-Summary-Malaysia-Gen-Med.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Keren-Wee_539_assignsubmission_file_3-poster_-Malaysia-General-Medicine.pdf">Malaysia &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Keren-Wee_539_assignsubmission_file_2-elective-summary_Malaysia-General-Medicine.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Claire-Hancock_338_assignsubmission_file_2-poster-malawi-responsible-elective-general-medicine.pdf">Malawi &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Claire-Hancock_338_assignsubmission_file_3-summary-malawi-responsible-elective-general-medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rachel-Mclean_323_assignsubmission_file_Poster-Malawi-OG-and-Paediatrics.pdf">Malawi &#8211; Obs&amp;Gynae/Paediatrics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rachel-Mclean_323_assignsubmission_file_Elective-Summary-Malawi-OG-and-Paediatrics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rebecca-Guy_305_assignsubmission_file_2.-Poster-Malawi-Paediatrics.pdf">Malawi &#8211; Paediatrics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rebecca-Guy_305_assignsubmission_file_3.-Summary-Malawi-Paediatrics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sunil-Stanislaus_315_assignsubmission_file_Stanislaus-Sunil-Malaysia-Emergency-and-Trauma-Orthopaedics-Eposter.pdf">Malaysia &#8211; Emergency &amp; Trauma/Orthopaedics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sunil-Stanislaus_315_assignsubmission_file_2-elective-summary-Malaysia-Emergency-and-Trauma-Orthopaedics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Avanus-Hong_586_assignsubmission_file_poster-Malaysia-Paediatrics-Ophthalmology-.pdf">Malaysia &#8211; Paediatrics and Ophthalmology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Avanus-Hong_586_assignsubmission_file_summary-Malaysia-Paediatrics-Ophthalmology-.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Danielle-Weeratunga_558_assignsubmission_file_2.-Poster-Malta-Endocrinology-and-Rheumatology.pdf">Malta &#8211; Endocrinology &amp; Rheumatology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Danielle-Weeratunga_558_assignsubmission_file_3.-Summary-Malta-Endocrinology-and-Rheumatology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Keren-Wee_1089_assignsubmission_file_3-poster-Malaysia-General-Medicine-AE-Paediatrics.pdf">Malaysia &#8211; General Medicine/A&amp;E/Paediatric ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Keren-Wee_1089_assignsubmission_file_2-elective-summary-Malaysia-General-Medicine-AE-Paediatrics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Thomas-Young_579_assignsubmission_file_3-Poster-Malawi-Tropical-Medicine.pdf">Malawi &#8211; Tropical Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Thomas-Young_579_assignsubmission_file_2-elective-summary-Malawi-Tropical-medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Anand-Palanisamy_1667_assignsubmission_file_3-poster-malaysia-generalmedicinepsychiatry.pdf">Malaysia &#8211; General Medicine &amp; Psychiatry ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Anand-Palanisamy_1667_assignsubmission_file_2-summary-malaysia-generalmedicinepsychiatry.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sean-Hawkey_1104_assignsubmission_file_2.-Poster-Malta-Dermatology-Cornwall-GP.pdf">Malta / UK, Cornwall &#8211; Dermatology and GP ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sean-Hawkey_1104_assignsubmission_file_3.-Elective-Summary-Malta-Dermatology-Cornwall-GP.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amy-Rice_54_assignsubmission_file_2-Poster-New-Zealand-Gen-Med-and-ED.pdf">New Zealand-Gen Med and ED</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Avril-Anderson_79_assignsubmission_file_3-poster.pdf">New Zealand -Neurosurgery</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Avril-Anderson_79_assignsubmission_file_2-elective-summary.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nathan-Wilson_56_assignsubmission_file_3-Elective-Poster-Hawaii-USA-NZ-Military-Med1.pdf">Hawaii &#8211; USA &#8211; </a><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nathan-Wilson_56_assignsubmission_file_3-Elective-Poster-Hawaii-USA-NZ-Military-Med.pdf">New Zealand &#8211; Military Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nathan-Wilson_56_assignsubmission_file_2-Elective-Summary-Hawaii-USA-NZ-Military-Med.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amber-Ogilvie_326_assignsubmission_file_3-poster-New-Zealand-Obstetrics-and-Gynaecology.pdf">New Zealand &#8211; Obs &amp; Gynae ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amber-Ogilvie_326_assignsubmission_file_2-elective-summary-New-Zealand-Obstetrics-and-Gynaecology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kaitlin-Mayne_324_assignsubmission_file_3-poster-New-Zealand-ICU.pdf">New Zealand &#8211; ICU ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kaitlin-Mayne_324_assignsubmission_file_2-elective-summary-New-Zealand-ICU.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Susan-Martin_325_assignsubmission_file_Martin-Susan-New-Zealand-Plastic-Surgery-Eposter.pdf">New Zealand &#8211; Plastic Surgery ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Susan-Martin_325_assignsubmission_file_Elective-Summary-New-Zealand-Plastic-Surgery-.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kirsty-Elliott_569_assignsubmission_file_Poster-New-Zealand-Paediatric-Anaesthesia-.pdf">New Zealand &#8211; Paediatric Anaesthetics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kirsty-Elliott_569_assignsubmission_file_Summary-New-Zealand-Paediatric-Anaesthesia-.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amy-Fitzpatrick_1094_assignsubmission_file_Poster-NewZealand-CriticalCare.pdf">New Zealand &#8211; Critical Care ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amy-Fitzpatrick_1094_assignsubmission_file_Summary-NewZealand-CriticalCare.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Barry-Kerr_1126_assignsubmission_file_Poster_N_Ireland_Trauma_Orthopaedics.pdf">Northern Ireland &#8211; Trauma and Orthopaedics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Barry-Kerr_1126_assignsubmission_file_Summary_N_Ireland_Trauma_Orthopaedics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Katherine-Gallagher_1113_assignsubmission_file_3-poster-NewZealand-anesthetics-ICU.pdf">New Zealand &#8211; Anaesthetics and ICU ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Katherine-Gallagher_1113_assignsubmission_file_2-summary-NZ-anaesthetics-ICU.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Arsh-Thakur_1091_assignsubmission_file_Poster-Philippines-Acute-Medicine-and-Surgery.pdf">Philippines &#8211; Acute Medicine and Surgery ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Arsh-Thakur_1091_assignsubmission_file_Summary-Philippines-Acute-Medicine-and-Surgery.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Becky-Webster_557_assignsubmission_file_3-Poster-Philippines-Psychiatry-and-Emergency-Department-.pdf">Philippines &#8211; Psychiatry and Emergency Medicine ePoster</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/James-Hill_552_assignsubmission_file_3-Poster-Philippines-GP.pdf">Philippines &#8211; General Practice ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/James-Hill_552_assignsubmission_file_2-Elective-Summary-Philippines-GP.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Leila-Ahmed_1139_assignsubmission_file_Poster-peru-genmed.pdf">Peru &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Leila-Ahmed_1139_assignsubmission_file_Elective-Summary-Peru-genmed.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Matthew-Hastings_1109_assignsubmission_file_Poster-The-Philippines-Internal-Medicine-and-Psychiatry.pdf">Philippines &#8211; Internal Medicine &amp; Psychiatry ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Matthew-Hastings_1109_assignsubmission_file_Summary-The-Philippines-Internal-Medicine-and-Psychiatry.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Aimee-Mallin_42_assignsubmission_file_2.-Poster-Scotland-Anaesthetics.pdf">Scotland-Anaesthetics</a>  <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Aimee-Mallin_42_assignsubmission_file_3.-Summary-Scotland-Anaesthetics.pdf">Summary- Scotland-Anaesthetics</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Anna-Wells_58_assignsubmission_file_3-poster-Malta-Wales-Scotland-Acute-and-Emergency.pdf">Malta Wales Scotland &#8211; Acute and Emergency</a><br />
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Anna-Wells_58_assignsubmission_file_2-summary-Malta-Wales-Scotland-Acute-and-Emergency.pdf">summary &#8211; Malta Wales Scotland &#8211; Acute and Emergency</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Chee-Lim_43_assignsubmission_file_2-Poster-Scotland-Public-Health.pdf">Scotland- Public Health</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Andrew-Ferguson_49_assignsubmission_file_3-poster-.pptx">Samoa &#8211; General Surgery</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Andrew-Ferguson_49_assignsubmission_file_2-elective-summary.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Heather-Robertson_33_assignsubmission_file_3-St-Lucia-EM-eposter.pdf">St Lucia &#8211; Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Heather-Robertson_33_assignsubmission_file_2-elective-St-Lucia-EM-summary.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Johanna-Jardine_50_assignsubmission_file-Saint-Vincent-and-the-Grenadines-Internal-medicine_ePoster.pdf"> Saint Vincent and the Grenadines &#8211; Internal medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Johanna-Jardine_50_assignsubmission_file_Summary-Saint-Vincent-and-the-Grenadines-Internal-medicine.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jordan-Burgess_30_assignsubmission_file_3-poster.pdf">Scotland &#8211; Acute Surgical Receiving Unit ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jordan-Burgess_30_assignsubmission_file_2-elective-Scotland-ASRU-summary.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Katherine-Woodroffe_37_assignsubmission_file_poster-St-Vincents-and-the-Grenadines-Paeds.pdf">St Vincent and the Grenadines &#8211; Paediatrics ePoster</a> and<a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Katherine-Woodroffe_37_assignsubmission_file_-elective-summary-St-Vincents-and-the-Grenadines-Paeds.pdf"> Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Pippa-Bell_51_assignsubmission_file_3-poster-Scotland-EM.pdf">Scotland &#8211; Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Pippa-Bell_51_assignsubmission_file_2-elective-summary-Scotland-EM.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rachel-John-Charles_61_assignsubmission_file_3-poster-St-Vincents-and-the-Grenadines-Gen-Surg.pdf">St Vincent and the Grenadines &#8211; General Surgery ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rachel-John-Charles_61_assignsubmission_file_2-elective-summary-St-Vincents-and-the-Grenadines-Gen-Surg.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rhona-Mcgregor_34_assignsubmission_file_3-poster_St-Vincents-and-the-Grenadines_Gen-Med.pdf">St Vincent and the Grenadines &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rhona-Mcgregor_34_assignsubmission_file_2-elective-summary_St-Vincents-and-the-Grenadines_Gen-Med.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rory-Gibson_25_assignsubmission_file_POSTER-SAMOA-SURGERY.pdf">Samoa &#8211; Surgery ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Rory-Gibson_25_assignsubmission_file_SUMMARY-SAMOA-SURGERY.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Andrew-Edwards_347_assignsubmission_file_3-poster-Orkney-General-Medicine.pdf">Scotland &#8211; Orkney &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Andrew-Edwards_347_assignsubmission_file_2-elective-summary-Orkney-General-Medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Angus-Forgie_322_assignsubmission_file_2-Poster-Saint-Vincents_Gen_Surgery.pdf">St Vincent &amp; Grenadines &#8211; General Surgery ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Angus-Forgie_322_assignsubmission_file_3-Summary-Saint-Vincents-General-surgery.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Anna-Johnstone_328_assignsubmission_file_3-poster-St-vincent-and-the-grenadines-anaesthetics.pdf">St Vincent &amp; Grenadine &#8211; Anaesthetics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Anna-Johnstone_328_assignsubmission_file_2-elective-summary-st-vincent-and-the-grenadines-anaesthetics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Benjamin-Smith_332_assignsubmission_file_Poster-Samoa-Anaesthetics.pdf">Samoa &#8211; Anaesthetics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Benjamin-Smith_332_assignsubmission_file_Summary-Samoa-Anaesthetics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Catherine-Geddie_401_assignsubmission_file_poster-St-Vincent-and-the-Grenadines-paediatrics.pdf">St Vincent &amp; Grenadines &#8211; Paediatrics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Catherine-Geddie_401_assignsubmission_file_Elective-summary-St-Vincent-and-the-Grenadines-paediatrics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Eilidh-Rice_317_assignsubmission_file_Poster-Scotland-Inverness-AE.pdf">Scotland, Inverness &#8211; Accident &amp; Emergency ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Eilidh-Rice_317_assignsubmission_file_2-electivesummary-Scotland-Inverness-AE.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Fraser-Arnott_310_assignsubmission_file_3-poster-South-Africa-Paediatric-Surgery.pdf">South Africa &#8211; Paedatric Surgery ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Fraser-Arnott_310_assignsubmission_file_2-elective-summary-South-Africa-Paediatric-Surgery.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Gareth-Lipton_308_assignsubmission_file_3-Poster-Sri-Lanka-Anaesthesia.pdf">Sri Lanka &#8211; Anaesthetics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Gareth-Lipton_308_assignsubmission_file_2-Elective-Summary-Sri-Lanka-Anaesthetics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Lucy-Elphinstone_335_assignsubmission_file_Poster-Scotland-Paediatric-Neurology.pdf">Scotland &#8211; Paediatric Neurology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Lucy-Elphinstone_335_assignsubmission_file_Summary-Scotland-Paediatric-Neurology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Mark-Neilly_309_assignsubmission_file_Poster-Samoa-Internal-Medicine.pdf">Samoa &#8211; Internal Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Mark-Neilly_309_assignsubmission_file_Summary-Samoa-Internal-Medicine-and-AE.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Shannon-Turkington_307_assignsubmission_file_3-Poster-Sri-Lanka-Oncology-and-Neurology.pdf">Sri Lanka &#8211; Oncology/Neurology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Shannon-Turkington_307_assignsubmission_file_2-Elective-Summary-Sri-Lanka-Oncology-and-Neurology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Alysha-Aikman_576_assignsubmission_file_2-poster-st-vincent-AE-OG.pdf">St Vincent &amp; Grenadines &#8211; Energency Medicine and Obs and Gynae ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Alysha-Aikman_576_assignsubmission_file_3-summary-st-vincent-AE-OG.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Emma-Lydon_581_assignsubmission_file_3-Poster-St-Vincent-Internal.pdf">St Vincent &amp; Grenadines &#8211; Internal Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Emma-Lydon_581_assignsubmission_file_2-Elective-Summary-St-Vincent-Internal.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ferdinand-Ravi_546_assignsubmission_file_3-Poster-Sri-Lanka-General-Medcine.pdf">Sri Lanka &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ferdinand-Ravi_546_assignsubmission_file_2-Summary-Sri-Lanka-General-medcine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Hui-Lu-Goh_568_assignsubmission_file_3-poster-Singapore-RadiologyAE.pdf">Singapore &#8211; Radiology and A &amp; E ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Hui-Lu-Goh_568_assignsubmission_file_2-elective-summary-Singapore-RadiologyAE.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jenn-Haw-Fong_580_assignsubmission_file_3-poster-Singapore-Neurosurgery-and-Emergency-Medicine.pdf">Singapore &#8211; Neurosurgery &amp; Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jenn-Haw-Fong_580_assignsubmission_file_2-elective-summary-Singapore-Neurosurgery-and-Emergency-Medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jill-Keohone_560_assignsubmission_file_3-poster-stvincent-anaesthetics.pdf">St Vincent &amp; Grenadines &#8211; Anaesthetics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jill-Keohone_560_assignsubmission_file_2-elective-summary-stvincent-anaesthetics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jonathan-Nairn_550_assignsubmission_file_Poster-Scotland-Paediatric-ENT.pdf">Scotland &#8211; Glasgow &#8211; Paediatric ENT ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jonathan-Nairn_550_assignsubmission_file_Summary-Scotland-Paediatric-ENT.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Krishnappan-Ramanathan_573_assignsubmission_file_Krishnappan-Ramanathan-Singapore-Infectious-Disease-Orthopedics.pdf">Singapore &#8211; Infectious Diseases &amp; Orthopaedics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Krishnappan-Ramanathan_573_assignsubmission_file_Elective-Summary-Sheet-Singapore-Krishnappan-Ramanathan.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Lewis-Tait_563_assignsubmission_file_ePoster-St-Vincent-The-Grenadines-Orthopaedics.pdf">St Vincent &amp; Grenadines &#8211; Orthopaedics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Lewis-Tait_563_assignsubmission_file_Elective-Summary-St-Vincent-The-Grenadines-Orthopaedics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sheryl-Chee_553_assignsubmission_file_3-poster-Singapore-OG-and-Anaesthetics.pdf">Singapore &#8211; Obs &amp; Gynae and Anaesthetics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sheryl-Chee_553_assignsubmission_file_2-electives-summary-Singapore-OG-and-Anaesthetics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Yong-Tan_556_assignsubmission_file_3-poster-Singapore-and-Malaysia-Obstetrics-and-Gynaecology.pdf">Singapore &#8211; Obs &amp; Gynae ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Yong-Tan_556_assignsubmission_file_2-elective-summary-Singapore-and-Malaysia-Obstetrics-and-Gynaecology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Yu-Lai_554_assignsubmission_file_Poster-SIngapore-Plastic-Orthopaedic-Surgery.pdf">Singapore &#8211; Plastics &amp; Orthopaedic Surgery ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Yu-Lai_554_assignsubmission_file_Summary-Singapore-Plastic-Orthopaedic-Surgery.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Aidan-Pritchard_1095_assignsubmission_file_Poster_Sri_Lanka_General_medicine.pdf">Sri Lanka &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Aidan-Pritchard_1095_assignsubmission_file_Summary_Sri_LANKA_General_Medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Annie-Irving_1134_assignsubmission_file_3-Poster-Scotland-Obstetrics-and-Gynaecology.pdf">Scotland &#8211; Obs &amp; Gynae ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Annie-Irving_1134_assignsubmission_file_2-Elective-Summary-Scotland-Obstetrics-and-Gynaecology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Eilidh-Bell_1135_assignsubmission_file_poster-scotland-radiology.pdf">Scotland &#8211; Radiology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Eilidh-Bell_1135_assignsubmission_file_elective-summary-scotland-radiology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Hwee-Fang-Lim_1128_assignsubmission_file_Poster-scotland-neurology.pdf">Scotland &#8211; Neurology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Hwee-Fang-Lim_1128_assignsubmission_file_Elective-summary-scotland-neurology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/John-Sinclair_1132_assignsubmission_file_Poster-Scotland-interventional-radiology.pdf">Scotland &#8211; Interventional Radiology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/John-Sinclair_1132_assignsubmission_file_Summary-Scotland-Interventional-radiology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Lauren-Dunlop_1110_assignsubmission_file_Poster-Sri-Lanka-Psychiatry.pdf">Sri Lanka &#8211; Psychiatry ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Lauren-Dunlop_1110_assignsubmission_file_Summary-Sri-Lanka-Psychiatry.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Stephanie-Scott-Flynn_1670_assignsubmission_file_2-poster.pdf">Scotland, Dundee / USA &#8211; Respiratory and Sports Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Stephanie-Scott-Flynn_1670_assignsubmission_file_3-elective-summary-.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Thomas-Linzee-Gordon_1675_assignsubmission_file_3-Poster-Scotland-RuralMedicine.pdf">Scotland, Orkney Islands &#8211; Rural Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Thomas-Linzee-Gordon_1675_assignsubmission_file_2-elective-summary-Scotland-RuralMedicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Diarmuid-Chevalier_341_assignsubmission_file_Poster-Togo-AE.pdf">Togo &#8211; Accident &amp; Emergency ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Diarmuid-Chevalier_341_assignsubmission_file_Summary-Togo-AE.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Mark-Mckane_327_assignsubmission_file_2-Poster-Tanzania-General-Medicine.pdf">Tanzania &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Mark-Mckane_327_assignsubmission_file_3-Summary-Tanzania-General-Medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Scott-Day_331_assignsubmission_file_2.-poster-Tanzania-medicine-surgery-paeds-palliative-obs-and-gynae.pdf">Tanzania &#8211; Multiple diciplines ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Scott-Day_331_assignsubmission_file_3.-summary-Tanzania-medicine-surgery-paeds-palliative-obs-and-gynae.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Tom-Mackenzie_337_assignsubmission_file_3-Poster-Tanzania-General-Medicine.pdf">Tanzania &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Tom-Mackenzie_337_assignsubmission_file_2-Elective-Summary-Tanzania-General-Medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Andrea-Ruscitto_1117_assignsubmission_file_3-poster-Tanzania-Paeds-OG.pdf">Tanzania &#8211; Paediatrics and Obs &amp; Gynae ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Andrea-Ruscitto_1117_assignsubmission_file_2-elective-summary-Tanzania-Paeds-OG.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sylvie-Aikman-Green_1097_assignsubmission_file_3.-Poster-Tanzania-Paediatrics.pdf">Tanzania &#8211; Paediatrics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sylvie-Aikman-Green_1097_assignsubmission_file_2.-Summary-Tanzania-Paediatrics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Chad-Ballantine_31_assignsubmission_file_3-poster.pdf">USA &#8211; Paediatrics</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Chad-Ballantine_31_assignsubmission_file_2-elective-summary.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nathan-Wilson_56_assignsubmission_file_3-Elective-Poster-Hawaii-USA-NZ-Military-Med1.pdf">Hawaii &#8211; USA &#8211; </a><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nathan-Wilson_56_assignsubmission_file_3-Elective-Poster-Hawaii-USA-NZ-Military-Med.pdf">New Zealand &#8211; Military Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nathan-Wilson_56_assignsubmission_file_2-Elective-Summary-Hawaii-USA-NZ-Military-Med.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Elizabeth-Headon_318_assignsubmission_file_2-poster-USA-Plastic-Reconstructive-surgery.pdf">USA &#8211; Plastic Reconstructive Surgery ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Elizabeth-Headon_318_assignsubmission_file_3.-Summary-USA-Plastics-Reconstructive-surgery.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Karen-Hamilton_339_assignsubmission_file_2-Poster-USA-General-Practice-and-Urgent-Care.pdf">USA &#8211; General Practice &amp; Urgent Care ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Karen-Hamilton_339_assignsubmission_file_3-USA-General-Practice-and-Urgent-Care.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ibrahim-Ibrahim_559_assignsubmission_file_3-Poster.pdf">United Arab Emirates &#8211; ENT ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ibrahim-Ibrahim_559_assignsubmission_file_2-Summary-UAE-ENT.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Paul-Smith_585_assignsubmission_file_2.Poster-UK-Paediatric-Neurology.pdf">UK &#8211; Edinburgh &amp; London &#8211; Paediatric Neurology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Paul-Smith_585_assignsubmission_file_3.Summary-UK-Paediatric-Neurology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Julie-Allison_1115_assignsubmission_file_Poster-United-States-Gynaecology.pdf">USA &#8211; Gynaecology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Julie-Allison_1115_assignsubmission_file_summary-united-states-gynaecology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nicola-Rogers_1116_assignsubmission_file_3-poster-UK-paediatrics.pdf">UK &#8211; Southampton / Angus &#8211; Comunity and General Paediatrics, Immunology and Allergy ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nicola-Rogers_1116_assignsubmission_file_2-elective-summary-UK-paediatrics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ryan-Leitch_1668_assignsubmission_file_Poster-UK-Anaesthesia-GP.pdf">UK &#8211; Anaesthesia &amp; GP ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ryan-Leitch_1668_assignsubmission_file_Summary-UK-Anaesthesia-GP.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sean-Hawkey_1104_assignsubmission_file_2.-Poster-Malta-Dermatology-Cornwall-GP.pdf">UK, Cornwall / Malta &#8211; GP and Dermatology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Sean-Hawkey_1104_assignsubmission_file_3.-Elective-Summary-Malta-Dermatology-Cornwall-GP.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Stephanie-Scott-Flynn_1670_assignsubmission_file_2-poster.pdf">USA / Scotland, Dundee &#8211; Sports Medicine &amp; Dermatology ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Stephanie-Scott-Flynn_1670_assignsubmission_file_3-elective-summary-.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amy-Sinclair_345_assignsubmission_file_2-poster-vietnam-generalmedicine-1.pdf">Vietnam &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Amy-Sinclair_345_assignsubmission_file_3-elective-summary-vietnam-generalmedicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Carla-Visocchi_334_assignsubmission_file_3-poster-Vanuatu-ObsGynae.pdf">Vanuatu &#8211; Obs &amp; Gynae ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Carla-Visocchi_334_assignsubmission_file_2-elective-summary-Vanuatu-ObsGynae.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kathryn-Garrett_336_assignsubmission_file_3-poster-vietnam-Gen-Med-Tropical-Ortho.pdf">Vietnam &#8211; General Medicine/Tropical Medicine/Orthopaedics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kathryn-Garrett_336_assignsubmission_file_2-elective-summary-Gen-Med-Tropical-Ortho.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Lyndsey-Harris_343_assignsubmission_file_3-poster-Vanuatu-paediatrics.pdf">Vanuatu &#8211; Paediatrics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Lyndsey-Harris_343_assignsubmission_file_2-elective-summary-Vanuatu-Paediatrics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nichola-Philp_306_assignsubmission_file_3-poster-Vanuatu-surgery.pdf">Vanuatu &#8211; Surgery ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Nichola-Philp_306_assignsubmission_file_2-elective-summary-Vanuatu-surgery.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Ally-Millar_1122_assignsubmission_file_Poster-Vietnam-Trauma-and-Orthopaedics-and-Tropical-Medicine.pdf">Vietnam &#8211; Trauma / Orthopaedics / Tropical Medicine ePoster</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Duncan-Renton_1114_assignsubmission_file_Poster-Vietnam-Orthopaedics.pdf">Vietnam &#8211; Orthopaedics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Duncan-Renton_1114_assignsubmission_file_Summary-Vietnam-Orthopaedics.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Owen-Mcdonald_1138_assignsubmission_file_3_Poster_Vietnam_CardioTropical.pdf">Vietnam &#8211; Cardiology &amp; Tropical Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Owen-Mcdonald_1138_assignsubmission_file_2_Elective_Summary_Vietnam_CardioTropical.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Anna-Wells_58_assignsubmission_file_3-poster-Malta-Wales-Scotland-Acute-and-Emergency.pdf">Malta Wales Scotland &#8211; Acute and Emergency</a><br />
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Anna-Wells_58_assignsubmission_file_2-summary-Malta-Wales-Scotland-Acute-and-Emergency.pdf">summary &#8211; Malta Wales Scotland &#8211; Acute and Emergency</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Aaron-Patterson_28_assignsubmission_file_Elective-Poster-Aaron-Patterson1.pdf">Zambia &#8211; Gen Surgery ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Aaron-Patterson_28_assignsubmission_file_2-elective-summary.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Dairshini-Sithambaram_57_assignsubmission_file_3-poster.pdf">Zambia &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Dairshini-Sithambaram_57_assignsubmission_file_2-elective-summary.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jessica-Dalzell_60_assignsubmission_file_2.-Poster-Zambia-Internal-Medicine.pdf">Zambia-Internal Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Jessica-Dalzell_60_assignsubmission_file_3.-Summary-Zambia-Internal-Medicine.pdf"> Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Johanna-Thonning_22_assignsubmission_file_3-Zambia-Paeds-and-Med-eposter.pdf">Zambia &#8211; Paediatrics and Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Johanna-Thonning_22_assignsubmission_file_2-elective-summary.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Maninee-Purohit_41_assignsubmission_file_3-poster-Zambia-Internal-Medicine.pdf">Zambia &#8211; Internal Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Maninee-Purohit_41_assignsubmission_file_2-elective-summary-Zambia-Internal-Medicine.pdf">Summary sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Frederick-Bainbridge_578_assignsubmission_file_3-Poster-Zanzibar-Acute-Care-and-Anaesthesia.pdf">Zanzibar &#8211; Anaesthetics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Frederick-Bainbridge_578_assignsubmission_file_2-Elective-Summary-Zanzibar-Anaesthetics-.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kevin-Hart_575_assignsubmission_file_Poster-Zanzibar-Medicine.pdf">Zanzibar &#8211; General Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Kevin-Hart_575_assignsubmission_file_Elective-Summary_Zanzibar-Medicine.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Stuart-Mcewan_566_assignsubmission_file_Poster-Zanzibar-Emergency.pdf">Zanzibar &#8211; Emergency Medicine ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Stuart-Mcewan_566_assignsubmission_file_Summary-zanzibar-emergency.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Joseph-Geoghegan_1119_assignsubmission_file_Poster-Zambia-Obstetrics-and-Gynaecology.pdf">Zambia &#8211; Obs &amp; Gynae ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Joseph-Geoghegan_1119_assignsubmission_file_Summary-Zambia-Obstetrics-and-Gynaecology.pdf">Summary Sheet</a></li>
<li><a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Mary-Rimbi_1133_assignsubmission_file_Poster-Zambia-General-Medicine-and-anaesthetics.pdf">Zambia &#8211; General Medicine &amp; Anaesthetics ePoster</a> and <a href="https://mbchb.dundee.ac.uk/electives/files/2016/02/Mary-Rimbi_1133_assignsubmission_file_Elective-Summary-Zambia-General-Medicine-and-Anaesthetics.pdf">Summary Sheet</a></li>
</ul>
</body>
</html>